# Generated by Django 4.0.4 on 2023-01-24 23:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ImageField(upload_to=blog.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(upload_to=blog.models.get_file_path),
        ),
    ]
