# Generated by Django 4.0.4 on 2023-02-01 12:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image_one_alter_blog_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_five',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_four',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_three',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
    ]
