# Generated by Django 4.0.4 on 2023-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_comment_is_active_alter_blockeduser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
