# Generated by Django 4.0.4 on 2023-01-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0014_comment_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
